### ISSUE TITLE
Undefined index: fbuser

### ISSUE THREAD

**Issue by ghost** [skjnldsv/Owncloud-FBSync#1]
When using the app, Owncloud 8.2, apache2, mysql

Undefined index: fbuser at /var/www/owncloud/apps/fbsync/templates/part.settings.php#9

**Comment by skjnldsv** [comment]
Hi!
Yep, totally forgot to remove that part of a previous version! :p 
Thanks!

**Comment by skjnldsv** [comment]
Fixed with commit ba2edb77b99f8954e1f4b5f0eaedd3c3f1daa581
