### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sinus23** [skjnldsv/Owncloud-FBSync#11]
So i have aktivate contacts in OC, than i installed the app fbsync. 
So if i klick on match contacts, oc error page
So if i klick on sync error too.
I started an update (8.2 to 8.2.x) so my cloud was broken...

**Comment by skjnldsv** [comment]
Hi!
I'm gonna need more info. What are the errors?

**Comment by skjnldsv** [comment]
Not enough informations.
