### ISSUE TITLE
Do not show photo thumbnails

### ISSUE THREAD

**Issue by KekcuHa** [skjnldsv/Owncloud-FBSync#12]
Doesn't show contacts photo both on "match contacts" and "sync matched" pages, but update photos.
![image](https://cloud.githubusercontent.com/assets/16463182/12018700/949050e2-ad77-11e5-8575-658c77645b8a.png)
![image](https://cloud.githubusercontent.com/assets/16463182/12018740/0fe5135e-ad78-11e5-8351-a3355bc3149a.png)

**Comment by RobertSmits** [comment]
Same problem here.
I tried to look at the problem and I think i found it.
The action to get the picture returns not the picture but the picture url as json in combination with a refresh header to the picture url. 
My guess is that for some reason the refresh header isn't working.

**Comment by skjnldsv** [comment]
Hi!! Thanks for your interest in this app.
Strange indeed! I will try something else to support both contacts app without the redirect header!

**Comment by skjnldsv** [comment]
You should be good now! :)
