### ISSUE TITLE
Use Facebooks API

### ISSUE THREAD

**Issue by enoch85** [skjnldsv/Owncloud-FBSync#13]
Great app, and thank you for the latest fixes, just tested it again, and no errors at all. NICE! Where can I donate?

As you stated yourself in the app, you don't use Facbooks API. This results in that you have to change language every time. Not so user friendly. Would it be possible to use their API in coming releases?

**Comment by enoch85** [comment]
Btw, my kudost to you! https://www.techandme.se/facebook-sync/

**Comment by skjnldsv** [comment]
Hi!
Thank you so much for your kind words! :)
The problem with their api is the fiend list. It's limited to the contacts who have enabled the graph api option. A lot of people disable this option (like me) to protect your account (no more like/recommends on foreign websites, no more apps that can use your account...) But it also close a lot of data.

If I had to enable and integrate the Facebook API, I would have to register this app in the facebook developper, and with the data I gather (birthdays for example), facebookk will require an approuval of this application. Which to be fair, is a lot more complicated for me than just making you change your language! :p 

So for now that's a no. I will be glad to integrate other function to this app on my free time, but recoding everything to fit the facebook's api requirement isn't in my todo list. :/

But don't forget that changing the language is only required to sync your birthdays. You shouldn't have to for the pictures! ;)

PS: no need to donate, seeing you happy is my only satisfaction!
