### ISSUE TITLE
Invalid Mimedir file. Line starting at 8 did not follow iCalendar/vCard conventions

### ISSUE THREAD

**Issue by sinus23** [skjnldsv/Owncloud-FBSync#14]
Sorry for the last Post.
Also i have hard Problems with your APP
So i installed this app correctly. 
Aktivate and go to the app. The first side with Note & Linke here its okay,
but after i aktivate my FB Account and go to Match contact or sync i have an Clouderror.
onsole: Uncaught ReferenceError: oc_appconfig is not defined(anonymous function) @ shareconfigmodel.js?v=99c17cea184fe557d219f1c0e30c872e:22(anonymous function) @ shareconfigmodel.js?v=99c17cea184fe557d219f1c0e30c872e:83

```
{
    "reqId":"3FyDiPWzzpoC76S2whm+",
    "remoteAddr":"85.16.70.180",
    "app":"index",
    "message":"Exception: {
    "Exception":"Sabre\VObject\ParseException",
    "Message":"Invalid Mimedir file. Line starting at 8 did not follow iCalendar/vCard conventions",
    "Code":0,
    "Trace":"
        #0 /var/www/owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(189): Sabre\VObject\Parser\MimeDir->readProperty(';UNKNOWN="MOBIL...')
        #1 /var/www/owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(137):Sabre\VObject\Parser\MimeDir->parseLine(';UNKNOWN="MOBIL...')
        #2 /var/www/owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(63):Sabre\VObject\Parser\MimeDir->parseDocument()
        #3 /var/www/owncloud/3rdparty/sabre/vobject/lib/Reader.php(44):Sabre\VObject\Parser\MimeDir->parse('BEGIN:VCARD??VE...',0)
        #4 /var/www/owncloud/apps/fbsync/app/contacts.php(56):Sabre\VObject\Reader::read('BEGIN:VCARD??VE...')
        #5 /var/www/owncloud/apps/fbsync/controller/pagecontroller.php(64):OCA\FbSync\App\Contacts->getList()
        #6[internal function]:OCA\FbSync\Controller\PageController->match()
        #7 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(159):call_user_func_array(Array,Array)
        #8 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(89):OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\FbSync\Controller\PageController),'match')
        #9 /var/www/owncloud/lib/private/appframework/app.php(108):OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\FbSync\Controller\PageController),'match')
        #10 /var/www/owncloud/lib/private/appframework/routing/routeactionhandler.php(45):OC\AppFramework\App::main('PageController','match',Object(OC\AppFramework\DependencyInjection\DIContainer),Array)
        #11[internal function]:OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
        #12 /var/www/owncloud/lib/private/route/router.php(291):call_user_func(Object(OC\AppFramework\routing\RouteActionHandler),
        Array)
        #13 /var/www/owncloud/lib/base.php(851):OC\Route\Router->match('/apps/fbsync/ma...')
        #14 /var/www/owncloud/index.php(39):OC::handleRequest()
        #15{main}",
    "File":"/var/www/owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php",
    "Line":385
    }",
    "level":3,
    "time":"2016-01-15T09:45:21+00:00"
}
```

by the way, if i can help, translate in german or any other, plz contact me ;) MY english to german very better than the other way round XD

**Comment by skjnldsv** [comment]
Hi!
It seems like you have a problem with one of your contacts.
Export your contacts as vcard, open it in a text editor and search for the line `UNKNOWN="MOBIL`
This contact doesn't follow the requirements of the vcard conventions. You need to edit this contact to fix your addressbook.

It's not due to my app :)
Keep me in touch.

**Comment by sinus23** [comment]
Sorry but this isnt correctly, while i havent any entries 
![cfda9e98-bb8a-11e5-9fbf-c4e28e32f091](https://cloud.githubusercontent.com/assets/14975046/12353769/c4e8ff5a-bb91-11e5-8406-ed3a4f39f00e.png)

I dont know wher he find this entry, but in my Vcard nothing. I can not do anything similar to entries in the SQL find

EDIT: image blurred for privacy issue

**Comment by sinus23** [comment]
I droped the Database entries. so its ok now. Thanks for the tipp with contact cards. But I still do not know where he has taken the entry.

Many many thanks

**Comment by skjnldsv** [comment]
So it's good now? :)

Ps: I've edited your image to blur personal data.

**Comment by sinus23** [comment]
I ´ve forgotten. Thanks. Yes it´s all good and works fine. Big Thx.
