### ISSUE TITLE
PHP Error prevents FB login 

### ISSUE THREAD

**Issue by wrapper** [skjnldsv/Owncloud-FBSync#16]
I get the following error in OwnCloud log when I attempt to use this plugin:

curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set at /dir/owncloud/apps/fbsync/controller/facebookcontroller.php#91

**Comment by skjnldsv** [comment]
Hi!
It's related to you php config. Please see http://stackoverflow.com/questions/6918623/curlopt-followlocation-cannot-be-activated

Keep me in touch :)
Regards.

**Comment by wrapper** [comment]
Quite odd, I did look this up and safe_mode is set to off and the open_basedir is set appropriately (I believe). Where should it be set if not as specified above?

**Comment by skjnldsv** [comment]
Good question. It may vary in a lot of configurations.
Did you reload your php config after your edit?

**Comment by wrapper** [comment]
Works after setting self_mode to off and disabling open_basedir
