### ISSUE TITLE
Unrecoverable error loading address books: Internal Server Error after syncing

### ISSUE THREAD

**Issue by wrapper** [skjnldsv/Owncloud-FBSync#17]
After installing the app and syncing with FB I get this error and can't CardDAV sync contacts anymore either.

Disabling app didn't fix it

**Comment by skjnldsv** [comment]
Hello!
I need more details about the error.
If you have an internal server error, you should be ale to get more details in your server logs.
Please reproduce and attach the log here (remove sensitive databefore posting it).

Regards.

**Comment by wrapper** [comment]
Error looks like this:

`{"reqId":"12312321","remoteAddr":"xxx","app":"carddav","message":"Exception: {\"Message\":\"End of document reached prematurely\",\"Exception\":\"Sabre\\\\VObject\\\\EofException\",\"Code\":0,\"Trace\":\"#0 \\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(133): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#2 \\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCARD\\\\r\\\\nVE...', 0)\\n#3 \\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(894): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCARD\\\\r\\\\nVE...')\\n#4 \\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(328): Sabre\\\\CardDAV\\\\Plugin->convertVCard('BEGIN:VCARD\\\\r\\\\nVE...', 'vcard4')\\n#5 \\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(255): Sabre\\\\CardDAV\\\\Plugin->addressbookMultiGetReport(Object(DOMDocument))\\n#6 [internal function]: Sabre\\\\CardDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'addressbooks\\\/us...')\\n#7 \\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(710): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#9 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#12 \\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/url\\\/url\\/url\\/default\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#14 \\\/url\\\/url\\/url\\/default\\\/remote.php(137): require_once('\\\/home\\\/drive\\\/sit...')\\n#15 {main}\",\"File\":\"\\\/url\\\/url\\/url\\/default\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":250}","level":4,"time":"2016-02-21T13:43:39+00:00"}`

and this:

`tact::retrieve Error parsing carddata  for: 2627 End of document reached prematurely","level":3,"time":"2016-02-21T20:40:37+00:00"}
{"reqId":"xxx","remoteAddr":"112323123","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 2627 End of document reached prematurely","level":3,"time":"2016-02-21T20:40:37+00:00"}
{"reqId":"xxx","remoteAddr":"112323123","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 2627 End of document reached prematurely","level":3,"time":"2016-02-21T20:40:37+00:00"}`

**Comment by skjnldsv** [comment]
What is your max_execution_time in your php settings?
Did you tried to revert the changes made to your php.ini?

**Comment by wrapper** [comment]
I increased it to 300 (5 minutes). I also get this error:

`Allowed memory size of 536870912 bytes exhausted (tried to allocate 436736000 bytes) at /folder/folder/default/apps/contacts/lib/utils/jsonserializer.php#86`

That's using 500+ MB!

**Comment by skjnldsv** [comment]
That's surprisingly high!
Can you try to export your contacts and check for inconsistent data? It seems that the contacts app is having trouble parsing the datas.

**Comment by wrapper** [comment]
I believe the problem is all of the embedded photo data in the vcard file is causing loading issues. With the photo data my vcard file is over 180,000 lines.

Any idea how I remove all of the photo data?

**Comment by skjnldsv** [comment]
If you can, fbsync has an option for that: https://yourdomain.com/index.php/apps/fbsync/contacts/delphotos

Make backups!!

Otherwize, you can try removing the PHOTO field in any text editors.

But it's strange, my contacts have a lot of pictures too, and I don't have any issue with 15k lines or more.

**Comment by wrapper** [comment]
I have a vcard backup but not sure I have a db backup..

I tried to run that but all it returns is a 0

**Comment by skjnldsv** [comment]
Any news? Did you successfully removed your old PHOTO field from all of your contacts?

**Comment by ggeorgg** [comment]
I also got an internal server error today when using your app to sync my contact pictures with my fb pictures again. I just removed index.php/apps/fbsync/status from my address line and I was redirected back to the files app. Now I get an internal server error when trying to match in your app again.
The first time I used your app no problems occured but today I got the following messages in the log file:

`filesize(): stat failed for /www/htdocs/xxxxx/domain.de/owncloud/data/user/fbsync.cookie at /www/htdocs/xxxxx/domain.de/owncloud/apps/fbsync/controller/facebookcontroller.php#329`

`OCA\Contacts\Contact::retrieve Error parsing carddata for: 161 End of document reached prematurely`

`Exception: {"Exception":"Sabre\\VObject\\EofException","Message":"End of document reached prematurely","Code":0,"Trace":"#0 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(133): Sabre\\VObject\\Parser\\MimeDir->readLine()\n#1 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\\VObject\\Parser\\MimeDir->parseDocument()\n#2 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\\VObject\\Parser\\MimeDir->parse('BEGIN:VCARD\\r\\nVE...', 0)\n#3 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/apps\/fbsync\/app\/contacts.php(56): Sabre\\VObject\\Reader::read('BEGIN:VCARD\\r\\nVE...')\n#4 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/apps\/fbsync\/controller\/pagecontroller.php(64): OCA\\FbSync\\App\\Contacts->getList()\n#5 [internal function]: OCA\\FbSync\\Controller\\PageController->match()\n#6 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\FbSync\\Controller\\PageController), 'match')\n#8 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\FbSync\\Controller\\PageController), 'match')\n#9 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('PageController', 'match', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/lib\/private\/route\/router.php(291): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/fbsync\/ma...')\n#13 \/www\/htdocs\/xxxxx\/domain.de\/owncloud\/index.php(39): OC::handleRequest()\n#14 {main}","File":"\/www\/htdocs\/xxxxx\/domain.de\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":250}`

Any idea what this is about? How can I easily figure out whos data is corrupted? Who is contact 161?

**Comment by ggeorgg** [comment]
So I have got two times this message `OCA\Contacts\Contact::retrieve Error parsing carddata for: 161 End of document reached prematurely` with two different numbers and I now just wanted to know what it is and so I counted the vcards in my .vcf file.
The vCards which are damaged are the only ones who have `PRODID:-//Sabre//Sabre VObject 3.4.7//EN`. All the other vCards have `PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN` or `PRODID:-//Apple Inc.//iOS 9.2//EN`
Another interessting thing could be that these vCards belonged to fb contacts with another name in my contact list so I matched them manually. Don't know if this is the problem because there also were other contacts I had match manually. 

I am using Contacts 0.5.0.0
With this damaged vCards my mobile phone isn't synching anymore over Davdroid. So for now I will just load my backup file into the contact app.

edit: After deleting my damaged contact adressbook, reimporting my backup file without pictures I synched the pictures again and I have no problems. So actually I don't know what messed up with my vCards because I can't reproduce this...

**Comment by skjnldsv** [comment]
Hi!
I can answer that! :)
Some users have reproduced the error. The problem with vcards si the compatibility between versions. the actual owncloud contact app use the last version (4.0) Some android roms uses the 2.0 or 3.0, newest version, the 4.0. I don't know for apple, but it may be similar.
And the problem when using different app to handle the same data is that some newer updated systems are actually overriding your vcards and consequently, making them obsolete for older contacts manager app.

You did right, the best way to handle this are exporting and reimporting the contacts since it will only parse and handle the fields that it understands.

**Comment by ggeorgg** [comment]
I really had some contacts with version 3.0 and some with version 4.0. So reimporting solved my problem and they are all on version 4.0 now.

Thanks for your replay! Great app and keep going ;)

**Comment by wrapper** [comment]
@skjnldsv the only solution I found was to remove the addressbook and reimport the vCard of my contacts into a separate one
