### ISSUE TITLE
No connection to FB

### ISSUE THREAD

**Issue by ggeorgg** [skjnldsv/Owncloud-FBSync#18]
Hey!
Im trying to get your app working in my owncloud but it seems that the app is not connecting to facebook. 
If I enter the right credentials I get a popup-message with "Connected to Facebook" like it should be (Owncloud-FBSync/js/login.js line 36).
The problem is, that it still shows "Facebook status: not connected" in the bottom left.

Furthermore I get an error-message in my admin log-file: 
curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set at /www/htdocs/xxxxx/domain.de/owncloud/apps/fbsync/controller/facebookcontroller.php#91 

What does this mean? How can I avoid this error and make the connection to facebook?
Has it something to do with my facebook safety configuration? 
Or is it a problem with my owncloud config.php.ini?   ('overwrite.cli.url' => 'https://www.domain.de/owncloud',)

My system: 
Owncloud new setup 8.2.2
PHP 5.5 (Modul)

**Comment by skjnldsv** [comment]
Hello! :)
It means you need to change your php settings.
open_basedir cannot be set for this app to work! :)

See https://github.com/skjnldsv/Owncloud-FBSync/issues/16#issuecomment-182333577

**Comment by vasyugan** [comment]
you mean it cannot be set _at all_? It seems that makes the app unsuitable for many installation.

**Comment by skjnldsv** [comment]
Apparently not! :)
I haven't had the time to look at it more precisely for now. sorry!
