### ISSUE TITLE
No images when owncloud in subdirectory

### ISSUE THREAD

**Issue by ggeorgg** [skjnldsv/Owncloud-FBSync#19]
Not really an issue but a problem I had because I installed owncloud in a subdirectory.
The links to the images were broken so I replaced the following two lines in app/contact.php by:
    `line 241:      $photo = "../../apps/contactsplus/getcontactphoto/".$this->id;`
    `line 244:      $photo = "../../apps/contacts/addressbook/".`

And thank you for your previous answer in my other issue!

**Comment by skjnldsv** [comment]
Hi!
Thanks, that could be a problem for some server settings indeed.
Thanks for your help.

**Comment by skjnldsv** [comment]
Should be fixed. :)
Please test https://github.com/skjnldsv/Owncloud-FBSync/releases/tag/v1.8-beta

And report here if okay.

**Comment by ggeorgg** [comment]
I will test this when OC 9 will work a bit better. I don't like the new contacts app because there is no vCard import option like in the old app. And I can't add contacts manually because of an string conversion error or something like that (didn't had a closer look at that problem yet).
I will look after this maybe next month...

**Comment by skjnldsv** [comment]
You can easily import your contacts manually in the database if you want 
:)

**Comment by enoch85** [comment]
I can confirm that the app is working perfect for me on ownCloud 9.
