### ISSUE TITLE
Error loading facebook friends. Are you connected?

### ISSUE THREAD

**Issue by ghost** [skjnldsv/Owncloud-FBSync#2]
I authenticate fine in the status page.
When I go to match all I get is, "Error loading facebook friends. Are you connected?"
I get several texts about my owncloud device trying to log in, but facebook seems to think it's a new device each time and tries to reauthenticate?
owncloud 8.2, mysql, apache2

**Comment by skjnldsv** [comment]
Do you have a cookie on your root owncloud installation folder?
It should be called "cookie.tmp"
If not, maybe is it a permission issue. 

Anyway, the cookie text file is only a temporary solution. I will probably find a better way or store the cookie in your owncloud data folder.

**Comment by ghost** [comment]
That solved it.
touch /var/www/owncloud/cookie.tmp
chown www-data:www-data /var/www/owncloud/cookie.tmp

**Comment by skjnldsv** [comment]
Fixed on the 1.0.0.
You can delete your cookie on the root folder or move it into your data/{yourusername} directory!

Thanks for your help!
