### ISSUE TITLE
No images when matching with owncloud after fresh installation

### ISSUE THREAD

**Issue by ggeorgg** [skjnldsv/Owncloud-FBSync#20]
Sorry it's me again.
I just played around a bit with your app and owncloud. After reporting issue #19 I wanted to setup a completly new owncloud instance and now I am not able to get images back when matching.

This time I used a subdomain oc.domain.de to avoid the error mentioned in #19. 

System:
PHP 5.6 (CGI)
Owncloud 8.2.2 (installed with the web-installer)
MySQL 5.6.27

A link to an image is for example https://oc.domain.de/index.php/apps/contacts/addressbook/local/1/contact/44/photo
When I follow this link in the browser I just get the following text:
{"data":{"FN":"prename name"}}

Before I started playing around it worked once and when I followed this link I really could see the image for the contact. Now I feel a bit helpless.

So do you know whats going wrong here?

Best regards
Georg

**Comment by skjnldsv** [comment]
hi!
Are you sure the contact 44 has a correct photo?

**Comment by ggeorgg** [comment]
That was the problem. It was not a correct photo.

I exported my contacts from owncloud and opened it with notepad. 
I had some contacts with a photo. Some of the lines began with `PHOTO;ENCODING=b;TYPE=image/jpeg:/9j/`, others began with `PHOTO:dataimage/jpegbase64/9j/`
Owncloud showed me an image when the line began with:
`PHOTO;ENCODING=b;TYPE=image/jpeg:/9j/`

I think the problem is that when I edit a contact on my Sony Xperia Z3 Compact the encoding is changed to `PHOTO:dataimage/jpegbase64/9j/` and owncloud and thunderbird can't display this as image. I think this is problem of different vCard versions but I am not sure about this. Don't know how to fix this but it's definitely not a bug of your app!
Do you know where I can ask for help to solve this because I don't want to loose my contact photos evereytime I change a contacts property on my mobile phone.

Thanks a lot!

**Comment by skjnldsv** [comment]
Hum, maybe try another contact app on you phone?
The vCard Format Specification says you need to specify the encoding: https://tools.ietf.org/html/rfc6350#section-6.2.4

Maybe your contact app is using an old version of vcard? 2.0? 1.0?

**Comment by ggeorgg** [comment]
Think my contact app uses vCard 2.0. Can see this when I export the contact list from my phone to my pc and open it with notepad. I will give this a try and I will inform you here if this helped.

**Comment by ggeorgg** [comment]
Think this is the solution:
https://github.com/gvde/contacts/commit/3dadadbfb9ce4d5b6b3437b49e06656f4bbb0caa
In owncloud 8.2.2 is still an old version of the contacts app which doesnt deal right with vCard 4.0 or something like that. After changing the code like in the link I didn't had this problem anymore.
Thanks a lot to you and keep going with your app! 
Great work!

**Comment by skjnldsv** [comment]
Thank you very much! Glad you found the problem :)
