### ISSUE TITLE
filesize(): stat failed /apps/fbsync/controller/facebookcontroller.php#329

### ISSUE THREAD

**Issue by ggeorgg** [skjnldsv/Owncloud-FBSync#21]
`filesize(): stat failed for /www/htdocs/xxxxx/domain.de/owncloud/data/user/fbsync.cookie at /www/htdocs/xxxxx/domain.de/owncloud/apps/fbsync/controller/facebookcontroller.php#329`

Maybe this it would be better to check if the file does not exist:
`if(!file_exists($this->userHome.$this->cookieName)) {`

Otherwise I always get this error in my oc log when opening the fb app in owncloud when I am not logged in to facebook. 
Or is there a reason to check for the filesize?

**Comment by skjnldsv** [comment]
Hi!
There was a reason. If the cookie exist but is empty, then the user can't be connected.
This avoid us to make a http request to see if the facebook user is connected.

(don't know if i'm very understandable :p)

**Comment by ggeorgg** [comment]
Is there a possibility that this file exists and it is empty? 
If I use the button to remove the stored credentials the file is deleted. And if this file does't exist, there will always be this filesize-error when trying to read the filesize of an non-exisiting file. 
So either the file is there and it was created by clicking the login button and it is not empty or it is not there because the app has just been activated or the owncloud user has deleted the user credentials previously).
So in my opinion !file_exists(...) makes more sense here than filesize(...).
Hope you understand what I mean ;)

**Comment by skjnldsv** [comment]
I understand perfectly! :)
There was a reason in the first releases, but I can't remember which ones! :p 
i will see that for the next one.

**Comment by skjnldsv** [comment]
Fixed.
Please see and test (_do backups_)
https://github.com/skjnldsv/Owncloud-FBSync/releases/tag/v1.8-beta
