### ISSUE TITLE
Is the app compatible with 9.0.0?

### ISSUE THREAD

**Issue by enoch85** [skjnldsv/Owncloud-FBSync#22]
Get this after update: `This app has no maximum ownCloud version assigned. This will be an error in ownCloud 11 and later.`

And the app is automatically deactivated. You should try to get this Approved,

**Comment by skjnldsv** [comment]
Not yet!
I will need to check everythings! :/

**Comment by skjnldsv** [comment]
Okay, maybe not everything, it shouldn't be too long i hope.
I need to fix the photos and the sync itself.

**Comment by enoch85** [comment]
Thanks!

**Comment by skjnldsv** [comment]
Please test https://github.com/skjnldsv/Owncloud-FBSync/releases/tag/v1.8-beta
Make backups!

**Comment by enoch85** [comment]
Thanks! Actually lost my phone to a pickpocket this weekend so I can't make a thorough test :/ Please announce the release of the beta so that others with ownCloud 9 can test.

**Comment by skjnldsv** [comment]
Sorry to hear that. :/
I already did. The beta was a quick test, I had few feedbacks, it was enough.
