### ISSUE TITLE
Little insignificant request

### ISSUE THREAD

**Issue by valentin8709** [skjnldsv/Owncloud-FBSync#24]
Hi! Thanks again for your work =) Just a little insignificant request from a maniacal guy: could you rename the app in the menu from "fbsync" to "FBsync", or with just one uppercase but every app name begin with an uppercase letter...

Sorry for that, and thank you!

**Comment by valentin8709** [comment]
Thank you very much =D

**Comment by skjnldsv** [comment]
:)
