### ISSUE TITLE
Get this app approved

### ISSUE THREAD

**Issue by enoch85** [skjnldsv/Owncloud-FBSync#26]
Hi John,

Now when you have joined the ownCloud team you should get this app approved IMHO. Check this out and talk to the devs: https://doc.owncloud.org/server/9.0/developer_manual/app/publishing.html#approved

Thanks for your great work!

**Comment by skjnldsv** [comment]
I need to rebuild this app before! :p 
Now that we have dav in core, I could go full javascript. I'm not really sure this app is 100% secure, I created it pretty easily, and didn't really make any audit on it for now. I will think of it later :)

Thanks!

**Comment by enoch85** [comment]
Please do rebuild it. Would be awesome.

Best regards
Daniel Hansson
www.techandme.se
Sent from Nexus 5x, sorry for typos.

**Comment by skjnldsv** [comment]
I'm not a developer full time, I don't really have a lot of free time these days! :/

**Comment by enoch85** [comment]
@skjnldsv I understand, I see you spend a lot of time in the ownCloud core apps though ;)

**Comment by skjnldsv** [comment]
Eheh! It's much quicker to fix some bugs here and there than rebuild an entire app ! ^^

**Comment by enoch85** [comment]
One small step at the time... :D I can ask around if any of my programmer friends are available to help you, @ezula maybe?

**Comment by skjnldsv** [comment]
:)
Well, it's a free opensource app! Anyone can rebuild it if they want.

**Comment by enoch85** [comment]
Now when it's in the Nextcloud Appstore (soonish) this issue is invalid, right? @skjnldsv

**Comment by ezula** [comment]
Oh, forgot to answer your question the 21:th of May 2016, sorry @enoch85 ;) Guess this is not relevant any more :)

**Comment by enoch85** [comment]
@ezula Hehe, better late than never. Ofc you are welcome to participate. :)
