### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by vasyugan** [skjnldsv/Owncloud-FBSync#27]
I enter my credentials and get a popup dialogue saying "you are now connected" but a message on the lower left corner says I am now. the following is in the log:

{"reqId":"ijmLHMxMteAPlgmN0Z05","remoteAddr":"87.160.149.111","app":"PHP","message":"curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set at \/var\/www\/user_web\/chroot\/htdocs\/org.org\/www\/oc\/apps\/fbsync\/controller\/facebookcontroller.php#91","level":3,"time":"2016-06-09T13:07:58+00:00"}
{"reqId":"dbN0G5X80eEJXLQWnXk4","remoteAddr":"87.160.149.111","app":"PHP","message":"curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir

  is set at \/var\/www\/user_web\/chroot\/htdocs\/org.org\/www\/oc\/apps\/fbsync\/controller\/facebookcontroller.php#91","level":3,"time":"2016-06-09T13:11:19+00:00"}

**Comment by skjnldsv** [comment]
See #18 :)
