### ISSUE TITLE
Syncing images causes SabreDAV exception

### ISSUE THREAD

**Issue by Gerii** [skjnldsv/Owncloud-FBSync#28]
Nextcloud version: 10.0.1
Contacts version: 1.4.0
FBSync version: 1.8.2

Syncing certain contacts with this app causes a broken address book. This causes the contacts app to fail to load completely (https://github.com/owncloud/contacts/issues/430) and it's also impossible to access the address book containing the broken contacts via CardDAV clients. The following error gets added to the log whenever someone tries to access the broken address book.
`Invalid Mimedir file. Line starting at 18 did not follow iCalendar/vCard conventions`

I can send you a vcf file containing a contact which will cause this issue once it has been synced with the app.

**Comment by skjnldsv** [comment]
Pleas send it! :)
Thanks.

**Comment by Gerii** [comment]
Couldn't find a way to contact you personally, but I was able to replace the image and other personal information, so I'm just going upload it here. Just rename it to vcf and import it via the contacts app and then sync it with any of your Facebook friends.
[Testfile.txt](https://github.com/skjnldsv/Owncloud-FBSync/files/541761/Testfile.txt)

**Comment by skjnldsv** [comment]
Does the line 18 matches the testfile? if not, what is on the line18?
You can contact me at skjnldsv@protonmail.com 😃

**Comment by Gerii** [comment]
In this case it was line 15, but the error only happens _after_ FBSync has been used on this particular contact. As is, the contact is still considered valid by SabreDAV. Unfortunately it's not possible to extract the contact once the address book is broken.

**Comment by skjnldsv** [comment]
do you have access to your database?
Or yo ucan go there to download your addressbook entirely: https://domain.name/remote.php/dav/addressbooks/users/

**Comment by Gerii** [comment]
Currently I don't have access, and the address book download is broken too once a contact in it is broken.

**Comment by skjnldsv** [comment]
Damn! This is going to be hard for as I don't know what is causing the issue! :/

**Comment by Gerii** [comment]
Can you reproduce it on your ownCloud/Nextcloud instance?

**Comment by skjnldsv** [comment]
I'm going to try! :)

**Comment by skjnldsv** [comment]
Welll, I can't reproduce, syncing works fine on my nc10 installation! :/

**Comment by Gerii** [comment]
That's weird. I will have a look at the database on the weekend if I find some time.
