### ISSUE TITLE
Get it running again and publish it to the Nextcloud appstore :)

### ISSUE THREAD

**Issue by jancborchardt** [skjnldsv/Owncloud-FBSync#29]
Hey @skjnldsv I didn’t realize this awesome app is made by you. :D I don’t have a Facebook account, but I think this kind of data migration tool is really great!

So let’s get this polished up and publish it to https://apps.nextcloud.com!

Then we can also work on some design improvements (I’m happy to contribute), and maybe even add more connectors like Twitter etc.

**Comment by skjnldsv** [comment]
Ahahaha, you're not the first to ask 😆 
This app is long time forgotten :)

I need to find the time to rebuild it from scratch, and I'm too busy with the scss and the contacts app :'(

**Comment by ghost** [comment]
FYI, if you add in the proper min and max versions for current Nextcloud, this app still works perfectly fine.

**Comment by skjnldsv** [comment]
@zerojay Yep, but will be broken on 12 😞

**Comment by Happyfeet01** [comment]
stop working in nextcloud 11

i get this warning:

```
Interner Serverfehler
Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.
Bitte wenden Sie sich an den Serveradministrator, wenn dieser Fehler mehrfach auftritt, geben Sie bitte die, unten stehenden, technischen Details in Ihrem Bericht mit an.
Weitere Details können im Server-Protokoll gefunden werden.

Technische Details
Entfernte Adresse: 151.252.220.134
Anfragekennung: nnUx4HZ9OXkkAJFfwDqs
```
and this:

```
Error
index
TypeError: Argument 3 passed to OCA\DAV\CardDAV\CardDavBackend::__construct() must implement interface OCP\IUserManager, instance of Symfony\Component\EventDispatcher\EventDispatcher given, called in /var/www/vhosts/Domain.tld/nextcloud/apps/fbsync/appinfo/application.php on line 64
```

**Comment by enoch85** [comment]
Would be great to get this in Nextcloud. My pictures haven't been updated for about a year.

**Comment by skjnldsv** [comment]
I knooooooow! 😢

**Comment by ghost** [comment]
It's working just fine for me here on Nextcloud 11.0.1. :)

**Comment by skjnldsv** [comment]
@zerojay It will stop soon when you update :p

**Comment by jancborchardt** [comment]
So at least increasing the max-version to 11 would be a quick fix. :)

**Comment by skjnldsv** [comment]
Please stop guys! This app won't be back soon. 😞
