### ISSUE TITLE
Issue white screen after starting app - no fetching images

### ISSUE THREAD

**Issue by apg1980** [skjnldsv/Owncloud-FBSync#3]
Hello,

i am using oc 8.2.1 with
Apache to 2.4.17
PHP to 5.5.29
MySQL to 5.6.25

i found some errors in log:
[Mon Nov 23 06:58:52.128795 2015] [:error] [pid 19971] [client 10.10.20.10:59623] PHP Parse error:  syntax error, unexpected '*', expecting ',' or ';' in /OWNCLOUD-DATA/opt/bitnami/apps/owncloud/htdocs/apps/fbsync/controller/facebookcontroller.php on line 40

i edited the line to private $cacheTime = 86400; the it was loading

The next issue after loading, no images are fetched.

Can you help?

thank you and best regards.

![fbs1](https://cloud.githubusercontent.com/assets/9514965/11330875/04b55d08-91b3-11e5-91ba-3fcd63615852.JPG)
![fbs2](https://cloud.githubusercontent.com/assets/9514965/11330887/23d2cd92-91b3-11e5-8ec0-41eb9970cbce.JPG)

**Comment by skjnldsv** [comment]
Hi @apg1980 !
Are you using contacts or contacts+?
On your screenshots, the app doesn't find any contacts. So no sync can be done.
Did you enabled at least one addressbook?

**Comment by apg1980** [comment]
i am using contacts.

**Comment by skjnldsv** [comment]
Do you have at least one addressbook enabled?

**Comment by skjnldsv** [comment]
I added errors messages on the last update.
Please try again and see if something changed! :)

**Comment by skjnldsv** [comment]
@apg1980 Any news? :)

**Comment by skjnldsv** [comment]
@apg1980 Hello? Please update.

**Comment by skjnldsv** [comment]
I'm closing this since this thread is dead.
