### ISSUE TITLE
Release for nextcloud 11

### ISSUE THREAD

**Issue by Mte90** [skjnldsv/Owncloud-FBSync#32]
I saw that in my installation with nextcloud 11 is not available and in the store is available only for the 11.

**Comment by jospoortvliet** [comment]
Any update on this, @skjnldsv  ?? ;-)

Just promoted the app over twitter but ofc - [this question came up quickly!](https://twitter.com/Gwmngilfen/status/845232411805921281)

**Comment by skjnldsv** [comment]
@jospoortvliet but this app is deaaad! :(
https://github.com/skjnldsv/fbsync/issues/29

**Comment by enoch85** [comment]
"Hey, let's create an app that many will like and then not maintain it."

Sorry, just had to.

**Comment by skjnldsv** [comment]
@enoch85 Since I'm not a dev anymore, I don't have the time to. 😢

**Comment by enoch85** [comment]
@skjnldsv But you created it right? So you should at least make it compatible with the latest versions. Please correct me if I'm wrong.

And about time, I spend all my free time on Tech and Me and the Nextcloud VM. Call me lonely, but it's all about priorities. ;)

**Comment by jancborchardt** [comment]
@jospoortvliet @skjnldsv @enoch85 maybe do a call for contributors over Twitter/Facebook/Google+? From the people who use it there’s gotta be some who can contribute to it.

**Comment by Mte90** [comment]
It is understandable that a dev doesn't have time when he is contributing to many projects (this happen to serious and addicted contributor) but I think that promote it or move in an organization can help to find someone that want to contribute. 
Actually this is a killer feature and I am using an app for Android for this but I think that is something that is better if run server side.

**Comment by enoch85** [comment]
@skjnldsv What is the required skills to maintain this? PHP?

**Comment by skjnldsv** [comment]
Php and js mostly.

**Comment by enoch85** [comment]
@ezula Perfect for you! :D

**Comment by ezula** [comment]
@enoch85 Maybe it is, but i'm not sure I have the time right now to dig into this.. :/

**Comment by jospoortvliet** [comment]
I've asked on twitter again, see if somebody bites ;-)

We could then perhaps move it to the Nextcloud project so multiple ppl could help, review etc.

**Comment by jancborchardt** [comment]
Yeah, this is quite a good data liberation app, so we should try and support it. @skjnldsv would you be up for moving it to the @Nextcloud organization?

cc @karlitschek @LukasReschke

**Comment by enoch85** [comment]
Yes please, could we move it to the Nextcloud organization?

**Comment by skjnldsv** [comment]
@jancborchardt Of course!

**Comment by jospoortvliet** [comment]
@LukasReschke can  you help move it?

**Comment by enoch85** [comment]
Ping @LukasReschke Please? :)

**Comment by skjnldsv** [comment]
I may have the time to work on it again this summer. I'll keep you updated on August. :)

**Comment by jospoortvliet** [comment]
Are you saying you will come to the Nextcloud Conference and give a talk about what you plan to do with the app? How great of you! We would be glad to sponsor your travel and hotel! Just sent me an email...


🙈 🙉 🙊

**Comment by skjnldsv** [comment]
@jospoortvliet Please, talk to my boss about it! 😂
More seriously, I'm sorry to decline this offer, I would love to, but can't. 🙁

**Comment by jospoortvliet** [comment]
that's very sad... Maybe next time 🎂  ?? 😀

**Comment by skjnldsv** [comment]
@jospoortvliet I would love to!!! 😊

**Comment by jospoortvliet** [comment]
Stay tuned as I'll already start talking to the TU about next year within a month after the end of the conference. Hopefully we'll have dates for 2018 by the end of this year 😄

**Comment by enoch85** [comment]
@jospoortvliet Sign me up! Will send you an email later.
