### ISSUE TITLE
Parse error: syntax error, unexpected '*', expecting ',' or ';'

### ISSUE THREAD

**Issue by wayneward** [skjnldsv/Owncloud-FBSync#4]
i just get a white screen nothing displays on the logs i get 

PHP Parse error:  syntax error, unexpected '*', expecting ',' or ';' in /var/www/owncloud/apps/fbsync/controller/facebookcontroller.php on line 40, referer: http://mydomain name/owncloud/index.php/apps/files/

**Comment by skjnldsv** [comment]
Hi! Edit the line and replace "24*60*60" by "86400".
Your config doesn't support the "24*60*60".

Update is coming this afternoon.

See issue #3

**Comment by wayneward** [comment]
confirmed works well thank you :+1:
