### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by JorgeGama** [skjnldsv/Owncloud-FBSync#5]
I installed this app on a fresh install of owncloud 8.2 and successfully activated it but when I try to use it with a non-admin account I am given a redirect loop error.

**Comment by skjnldsv** [comment]
Hi!!
I'm only using an admin account. I will try to reproduce the bug on my system.
Thanks for reporting this bug! :)

**Comment by skjnldsv** [comment]
Bug reproduced! Working on the fix right now.

**Comment by skjnldsv** [comment]
Here you go! :)
Sorry for the bug, thanks for finding it! ;)
