### ISSUE TITLE
Bug: birthday Sync

### ISSUE THREAD

**Issue by valentin8709** [skjnldsv/Owncloud-FBSync#6]
After sync, all my contacts have the same birthday... Here is what I found in owncloud logs:

filemtime(): stat failed for /media/DATA/valou/cache/show-contacts-foto-20 at /var/www/owncloud/lib/private/files/storage/local.php#156
filemtime(): stat failed for /media/DATA/valou/cache/editphoto at /var/www/owncloud/lib/private/files/storage/local.php#156
filemtime(): stat failed for /media/DATA/valou/cache/show-contacts-foto-20 at /var/www/owncloud/lib/private/files/storage/local.php#156

If you need another log or anything else, tell me.
Thanks for your support =)

**Comment by skjnldsv** [comment]
Hi! Thanks for posting this here! :)
Which date is set as birthday? Does it match with at least one contact?
Are you using an admin account or a regular one?

**Comment by valentin8709** [comment]
It is 27, november 2015 (the sync date infact...). I'm using an admin account.

**Comment by skjnldsv** [comment]
Could you try a sync after updating this release?
https://1fichier.com/?hrfnf7zf4d

I modified the output of the birthdaysand disabled the contacts data saving.
So when you will sync, the contacts miniatures will have the exact text taken from the facebook instance in their tooltip.

Please give me the tooltips data :)

![capture d ecran_2015-11-27_12-01-42](https://cloud.githubusercontent.com/assets/14975046/11439902/b76988b8-94fe-11e5-9c23-c922e753d997.png)

**Comment by valentin8709** [comment]
The app tells my contacts already have a birthday... So I deleted a birthday for one contact, and now I have an infinite sync =(

**Comment by skjnldsv** [comment]
Infinite sync? Like it keep the sync screen on?
If so, there should be an error. Open the console (F12 on chrome) and check for errors on the "console" tab! :)

**Comment by valentin8709** [comment]
Okay sync works now... but I have a "false" instead of birthday:
![fb_sync_bug](https://cloud.githubusercontent.com/assets/6785619/11449198/c028aca4-956c-11e5-979a-fa5343073aff.png)

**Comment by skjnldsv** [comment]
That's what I wanted! 
Pretty strange. Maybe your facebook seup is different than mine. I'm loking into it :)

**Comment by skjnldsv** [comment]
Okay, the false should come from the function getBirthday($fbid)
located here: https://github.com/skjnldsv/Owncloud-FBSync/blob/master/controller/facebookcontroller.php#L239

Could you replace the 4 "return false"on this function with 1, 2, 3 and 4.
And tell me which one appear on the tooltip, :)
Thanks for your patience.

**Comment by valentin8709** [comment]
If I have understood well, you want me to replace "return false;" by "return 1;" for the 4 return in the function getBirthDay() (then try with 2, 3, 4) ?
Another point: The birthday is not fixed, I checked today and all my contacts have november, 28th as birthday... So it just prints the current date.

No problem, I really like your app so I will do (almost) anything to have a stable version =)

**Comment by skjnldsv** [comment]
Yep, exaclty :)
Whatever order you chose for the 1, 2, 3, 4. The point is just to differenciates the returns so I can know where it doesn't work

**Comment by valentin8709** [comment]
I tried with the lase version (1.4), tried return 1; (2, 3, 4, and false) and all my contacts are ignored in the sync... 
Also, could you do an option to erase every birthday for all contacts? 

Thank you for your help and your work =)

**Comment by skjnldsv** [comment]
Did you delete one birthday like your previous test?
And no problem, will do a button to remove al picture and all birthdays. Good idea! :)

**Comment by skjnldsv** [comment]
Found it!
Please update and report again :)
